#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://paritosh:Paritosh%402000@cluster0.egx5c.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#spring.security.user.name=user
#spring.security.user.password=user
spring:
  kafka:
#    bootstrap-servers: aws.confluent.cloud:9092
    bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='XZGYRXDXVXUNDTVP' password='36tcOfQxbjkS00iANYigsKE5B+5FL7iyZkEiKgOx1miQ9833IXhXJIDjBGqdv05L';
      session:
        timeout:
          ms: 45000
  redis:
    uri: redis-cli -u redis://default:y1qjdegVuAOyExNEEuWHBrW1CaVBHVm4@redis-17408.c264.ap-south-1-1.ec2.redns.redis-cloud.com:17408
  data:
    mongodb:
      uri: mongodb+srv://paritosh:Paritosh%402000@cluster0.egx5c.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  profile:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: paritoshmathur1212@gmail.com
    password: bfdk rmda lnwt llty
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    net:
      engineeringdigest:
        journalApp: DEBUG
weather:
  api:
    key: 6595b05c84010ae9c15a99dacee99070


